#!/usr/bin/env bash
#
# Summary: Shows a list of tmux sessions and attaches to the one chosen by user
#
# Usage: {cmd}
#
# This is meant to be run indefinitely
# When you detach a session, you are right back at choosing a session.
# Use [Esc] or Ctrl+c to end.

while true; do
  session=$(tmux ls -F '#{session_name}' | fzf --prompt="Choose a tmux session or hit escape> " --preview="tmux capture-pane -ep -t {} | tail -30" --layout=reverse)
  fzf_status=$?

  # Exit on any error
  [ $fzf_status -gt 0 ] && break

  # Attach if a session was selected
  [ -n "$session" ] && tmux -CC attach -t "$session"
done
