#!/usr/bin/env bash
#
# Summary: TBD
#
# Usage: {cmd} [pull-request-url]

BASH_OPTS="-eo pipefail ${DEBUG+-x}"
set ${BASH_OPTS}

PULL_REQUEST_URL=$1

if [ -z "${PULL_REQUEST_URL}" ]; then
  read -p "Pull request URL for which you'd like to see the plan: " PULL_REQUEST_URL
fi
REPOSITORY=$(gh pr view --json headRepository --jq '.headRepository.name' ${PULL_REQUEST_URL})

INFO=$(gh pr view ${PULL_REQUEST_URL} --json headRefName,headRepository,headRepositoryOwner,number --jq '{number, repository: .headRepository.name, owner: .headRepositoryOwner.login, branch: .headRefName, repositoryWithOwner: "\(.headRepositoryOwner.login)/\(.headRepository.name)"}')
BRANCH=$(echo ${INFO} | jq -r .branch)
REPO=$(echo ${INFO} | jq -r .repositoryWithOwner)

echo We\'re talking about branch: ${BRANCH} in repo ${REPO}

WORKDIR=~/work/${REPOSITORY}

echo "Going to ${WORKDIR}"

cd ${WORKDIR}
gh pr checkout ${PULL_REQUEST_URL}

#################
# Trigger a plan
#################
# Fetch projects for this PR:
PR_NUMBER=$(echo ${INFO} | jq -r .number)
OWNER=$(echo ${INFO} | jq -r .owner)
REPO_WITHOUT_OWNER=$(echo ${INFO} | jq -r .repository)

MODULE_TO_APPLY=$(gh api graphql --paginate -F name="${REPO_WITHOUT_OWNER}" -F owner="${OWNER}" -F number="${PR_NUMBER}" -f query='
query($number: Int!, $name: String!, $owner: String!, $endCursor: String) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      projectsV2(first: 100, after: $endCursor) {
        nodes {
          id
          number
          title
        }
      }
    }
  }
}' \
| jq -r '.data.repository.pullRequest.projectsV2.nodes | map(.title) | .[]' \
| sort \
| fzf --height ~20% --select-1 --prompt="Choose a module to apply> ")

if [ -f .github/workflows/terraform-apply-all.yml ]; then
  WORKFLOW=terraform-apply-all.yml
elif [ -f .github/workflows/terraform-apply.yml ]; then
  WORKFLOW=terraform-apply.yml
else
  echo "Cannot determine which workflow to run"
  exit 1
fi

sd github workflow inputs .github/workflows/${WORKFLOW} \
| jq --arg module $MODULE_TO_APPLY '. + { $module }' \
| tee /dev/stderr \
| gh workflow run ${WORKFLOW} --repo ${REPO} --ref ${BRANCH} --json

gh run list --repo ${REPO} --workflow=${WORKFLOW} --branch ${BRANCH}
