#!/usr/bin/env bash
#
# Summary: Create CodeSpace in current repo and SSH into it
#
# Usage: {cmd} [pull-request-url]

BASH_OPTS="-eo pipefail ${DEBUG+-x}"
set ${BASH_OPTS}

PULL_REQUEST_URL=$1

if [ -z "${PULL_REQUEST_URL}" ]; then
  read -p "Pull request URL for which you'd like to set up a codespace: " PULL_REQUEST_URL
fi

REPOSITORY=$(gh pr view --json headRepository --jq '.headRepository.name' ${PULL_REQUEST_URL})

WORKDIR=~/work/${REPOSITORY}

echo "Going to ${WORKDIR}"

cd ${WORKDIR}
gh pr checkout ${PULL_REQUEST_URL}

CURRENT_REPO=$(gh repo view --json nameWithOwner -q ".nameWithOwner")
CURRENT_BRANCH=$(git rev-parse --abbrev-ref head)

echo "Creating CodeSpace in ${CURRENT_REPO} on branch ${CURRENT_BRANCH}"

SMALLEST_AVAILABLE_CODESPACE=$(gh api \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /repos/{owner}/{repo}/codespaces/machines \
  | jq -r '.machines | sort_by(.memory_in_bytes)[0].name')

NEW_CODESPACE=$(gh cs create \
  --devcontainer-path .devcontainer/devcontainer.json \
  --repo ${CURRENT_REPO} \
  --branch ${CURRENT_BRANCH} \
  --machine ${SMALLEST_AVAILABLE_CODESPACE})

gh cs ssh --codespace ${NEW_CODESPACE}
