#!/usr/bin/env bash
#
# Summary: List relevant repositories
#
# Usage: {cmd} [ --archived ]

BASH_OPTS="-eo pipefail ${DEBUG+-x}"
set ${BASH_OPTS}

declare -A args="($_SD_ARGS)"

gh search repos \
  --owner $GITHUB_EMPLOYER_ORGS \
  --topic terraform --topic infrastructure \
  --match name \
  --limit 100 \
  --json fullName \
  --archived=${args[archived]} \
  infrastructure \
| jq -r 'map(.fullName) | .[]' \
| sort
