#!/usr/bin/env bash
#
# Summary: List relevant repositories
#
# Usage: {cmd} [ --archived ]

BASH_OPTS="-eo pipefail ${DEBUG+-x}"
set ${BASH_OPTS}

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --archived) ARCHIVED=true;;
    *) echo "Unknown parameter passed: $1"; exit 1 ;;
  esac
  shift
done

gh search repos \
  --owner $GITHUB_EMPLOYER_ORGS \
  --topic terraform --topic infrastructure \
  --match name \
  --limit 100 \
  --json fullName \
  --archived=${ARCHIVED-false} \
  infrastructure \
| jq -r 'map(.fullName) | .[]'
