#!/usr/bin/env bash
#
# Summary: Bulk-review pull requests
#
# Usage: {cmd} [pull-numbers-or-urls]...
#
# Takes a set of pull request numbers or pull request URLs
# and shows their diff, asking for approval.
#
# To show review all Dependabot pull requests in bulk, pass:
# (gh pr list --author app/dependabot --json number | jq -r 'map(.number) | .[]')

BASH_OPTS="-eo pipefail ${DEBUG+-x}"
set ${BASH_OPTS}

PULL_REQUESTS=$@

tr ' ' '\n' <<< "${PULL_REQUESTS}" \
  | fzf --multi --preview='gh pr diff {}' \
  | xargs -I {} gh pr review {} --approve

