#!/usr/bin/env bash
#
# Summary: Gets temporary credentials
#
# Usage: {cmd} --profile=PROFILE [ --role-name=ROLE ]
#
# This script is useful for fetching temporary credentials for a role via AWS SSO.
# The access token and region is taken from the latest cache file in
# ~/.aws/sso/cache.
#
# The output is a JSON that can be piped to local file to use further.

declare -A args="($_SD_ARGS)"

account_id=$(aws configure get profile.${args[profile]}.sso_account_id)
latest_cache_file=$(ls -t1 ~/.aws/sso/cache/*.json | head -n 1)
access_token=$(cat ${latest_cache_file} | jq -r '.accessToken')
region=$(cat ${latest_cache_file} | jq -r '.region')

aws sso get-role-credentials \
  --profile ${args[profile]} \
  --role-name ${args[role-name]:-fullaccess} \
  --account-id ${account_id} \
  --access-token "${access_token}" \
  --region ${region}
