#!/usr/bin/env bash
#
# Summary: Taint individual resources in a given environment and apply the changes
#
# Usage: {cmd} <environment> tf_resource.to_be_tainted [more_resources … ]

export ENVIRONMENT=$1

shift 1
RESOURCES=$@

# ####################################
# initialize TF state
# ####################################
make init

for RESOURCE in ${RESOURCES}; do
  terraform taint ${RESOURCE}
done

make apply
